# Generated by Django 3.2.6 on 2021-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generated',
            name='image',
        ),
        migrations.AddField(
            model_name='generated',
            name='url_image',
            field=models.ImageField(default=1, upload_to='image/'),
            preserve_default=False,
        ),
    ]
