# Generated by Django 3.2.6 on 2021-08-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210811_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generated',
            old_name='url_image',
            new_name='image',
        ),
    ]
