# Generated by Django 3.2.6 on 2021-11-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_url_image_generated_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Generated',
        ),
    ]
